name: Linting

on:
  push:

jobs:
  flake8:
    name: "Flake8"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Setup python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: "Installing dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: "Run flake8"
        run: task lint_flake8
      - name: "Run mypy"
        run: task lint_mypy
      - name: "Run isort"
        run: task lint_isort
