name: Automated tests

on:
  push:

jobs:
  tests:
    name: "Automated tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Setup python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: "Setup ffmpeg"
        uses: FedericoCarboni/setup-ffmpeg@v1
      - name: "Installing dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: "Run tests"
        run: poetry run task test
